---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    jmeter_servers:
      hosts:
        jmeter11:
        jmeter12:
        jmeter13:
      vars:
        munin_master_ip_address_regexp: ^10\.146\.0\.2$
